<header>
	<div class="container">
		<div class="row">
			<nav class="navbar navbar-expand-lg">
				<dnn:Logo runat="server" id="dnnLogo" />
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<dnn:MENU MenuStyle="menus/main" runat="server" NodeSelector="*"></dnn:MENU>
			</nav>
		</div>
	</div>
</header>