<nav class="navbar navbar-expand-lg">

	<dnn:LOGO runat="server" ID="DnnLogo" class="navbar-brand" />

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<dnn:MENU ID="MENU" MenuStyle="menus/main" runat="server" NodeSelector="*"></dnn:MENU>
	
</nav>