<div class="container">
	<div class="row">

		<nav class="navbar navbar-light navbar-expand-lg">

			<dnn:LOGO runat="server" class="navbar-brand" />

			<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon">
					<span></span>
					<span></span>
					<span></span>
					<span></span>
					<span></span>
					<span></span>
				</span>
			</button>

			<dnn:MENU MenuStyle="menus/main" runat="server" NodeSelector="*"></dnn:MENU>
		</nav>
		
	</div>
</div>